[
	uuid(4c9dbf19-d39e-4bb9-90ee-8f7179b20283),
	version(1.0),
]
interface DefaultIfName
{

	typedef struct Struct_12_t
	{
		long 	StructMember0;
		short 	StructMember1;
		short 	StructMember2;
		byte 	StructMember3[8];
	}Struct_12_t;

	typedef struct Struct_24_t
	{
		struct Struct_12_t 	StructMember0;
	}Struct_24_t;

	typedef struct Struct_102_t
	{
		struct Struct_12_t 	StructMember0;
		hyper 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		hyper 	StructMember4;
		/* enum_16 */ short 	StructMember5;
	}Struct_102_t;

	typedef struct Struct_164_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		long 	StructMember4;
		long 	StructMember5;
		long 	StructMember6;
		long 	StructMember7;
		long 	StructMember8;
	}Struct_164_t;

	typedef struct Struct_182_t
	{
		long 	StructMember0;
		long 	StructMember1;
	}Struct_182_t;

	typedef struct Struct_274_t
	{
		/* enum_16 */ short 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
	}Struct_274_t;

	typedef struct Struct_320_t
	{
		struct Struct_12_t 	StructMember0;
		struct Struct_12_t 	StructMember1;
		long 	StructMember2;
	}Struct_320_t;

	long Proc0_UtcApi_IsScenarioActive(
		[in]struct Struct_24_t* arg_1,
		[out]long* arg_2);

	long Proc1_UtcApi_EscalateScenario(
		[in]struct Struct_24_t* arg_1,
		[in]/* enum_16 */ short arg_2,
		[in][string] wchar_t* arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]long arg_6,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_8);

	long Proc2_UtcApi_EscalateScenarioAsync(
		[in]struct Struct_24_t* arg_1,
		[in]/* enum_16 */ short arg_2,
		[in][string] wchar_t* arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]long arg_6,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_8);

	long Proc3_UtcApi_IsEscalationRunning(
		[in]struct Struct_24_t* arg_1,
		[out]long* arg_2);

	long Proc4_UtcApi_DownloadLatestSettingsForNamespace(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]long arg_5);

	long Proc5_UtcApi_DownloadLatestSettingsForNamespaceAsync(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]long arg_5);

	long Proc6_UtcApi_GetActiveScenarioList(
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_2)] /*  */ struct Struct_24_t** arg_1,
		[out]long* arg_2);

	long Proc7_UtcApi_ForceUpload(
		[in]char arg_1,
		[in]long arg_2,
		[in]long arg_3);

	long Proc8_UtcApi_ResetUsageMetrics(
	);

	long Proc9_UtcApi_IsTraceRunning(
		[in]/* enum_16 */ short arg_1,
		[in]struct Struct_102_t* arg_2,
		[out][ref]/* enum_16 */ short* arg_3);

	long Proc10_UtcApi_GetActiveTraceRuntime(
		[in]/* enum_16 */ short arg_1,
		[out]hyper* arg_2,
		[out]hyper* arg_3);

	long Proc11_UtcApi_GetKnownTraceList(
		[in]/* enum_16 */ short arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_3)] /*  */ struct Struct_102_t** arg_2,
		[out]long* arg_3);

	long Proc12_UtcApi_DownloadLatestSettings(
		[in]long arg_1,
		[in]long arg_2);

	long Proc13_UtcApi_ReloadSettings(
	);

	long Proc14_UtcApi_UpdateTimerConfiguration(
		[in][string] wchar_t* arg_1,
		[in]struct Struct_164_t* arg_2);

	long Proc15_UtcApi_ClearTimerConfiguration(
		[in][string] wchar_t* arg_1);

	long Proc16_UtcApi_GetNextScheduledFireTime(
		[in][string] wchar_t* arg_1,
		[out]long* arg_2,
		[out]struct Struct_182_t* arg_3);

	long Proc17_UtcApi_GetTimerConfiguration(
		[in][string] wchar_t* arg_1,
		[out]struct Struct_164_t* arg_2,
		[out]long* arg_3);

	long Proc18_UtcApi_GetCustomTraceList(
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_2)] /*  */[string] wchar_t*** arg_1,
		[out]long* arg_2);

	long Proc19_UtcApi_StartCustomTrace(
		[in][string] wchar_t* arg_1,
		[in]hyper arg_2);

	long Proc20_UtcApi_SnapCustomTrace(
		[in][string] wchar_t* arg_1);

	long Proc21_UtcApi_StopCustomTrace(
	);

	long Proc22_UtcApi_EscalateScenario2(
		[in]struct Struct_24_t* arg_1,
		[in]/* enum_16 */ short arg_2,
		[in][string] wchar_t* arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]/* enum_16 */ short arg_6,
		[in]long arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_7)] /*  */[string] wchar_t** arg_8,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_7)] /*  */[string] wchar_t** arg_9);

	long Proc23_UtcApi_EscalateScenarioAsync2(
		[in]struct Struct_24_t* arg_1,
		[in]/* enum_16 */ short arg_2,
		[in][string] wchar_t* arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]/* enum_16 */ short arg_6,
		[in]long arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_7)] /*  */[string] wchar_t** arg_8,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_7)] /*  */[string] wchar_t** arg_9);

	long Proc24_UtcApi_GetActiveTraceInfo(
		[in]/* enum_16 */ short arg_1,
		[out]struct Struct_102_t* arg_2);

	long Proc25_UtcApi_EnableWERLocalReports(
	);

	long Proc26_UtcApi_RestoreWERLocalReportsSettings(
	);

	long Proc27_UtcApi_QueryWERLocalReportsEnabled(
		[out][ref][string] wchar_t** arg_1);

	long Proc28_UtcApi_IsEscalationRunningEx(
		[in]struct Struct_24_t* arg_1,
		[out]long* arg_2,
		[out]struct Struct_12_t* arg_3);

	long Proc29_UtcApi_QueryDiagnosticCollectionState(
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_2)] /*  */ struct Struct_274_t** arg_1,
		[out]long* arg_2);

	long Proc30_UtcApi_EscalateScenario3(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]/* enum_16 */ short arg_5,
		[in]long arg_6,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_8,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_10)] /*  */ struct Struct_320_t** arg_9,
		[out]long* arg_10);

	long Proc31_UtcApi_GetIdsFromCategory(
		[in][string] wchar_t* arg_1,
		[out][ref][size_is(, *arg_3)]long** arg_2,
		[out]long* arg_3);

	long Proc32_UtcApi_GetRunningTraces(
		[in][string] wchar_t* arg_1,
		[out][ref][size_is(, *arg_3)]long** arg_2,
		[out]long* arg_3);

	long Proc33_UtcApi_GetContextProperty(
		[in][string] wchar_t* arg_1,
		[out][ref][string] wchar_t** arg_2);

	long Proc34_UtcApi_GetRunningEscalationsForContext(
		[in][string] wchar_t* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_3)] /*  */ struct Struct_320_t** arg_2,
		[out]long* arg_3);

	long Proc35_UtcApi_EscalateScenarioAsync3(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]/* enum_16 */ short arg_5,
		[in]long arg_6,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_7,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_6)] /*  */[string] wchar_t** arg_8,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_10)] /*  */ struct Struct_320_t** arg_9,
		[out]long* arg_10);

	long Proc36_UtcApi_GetApiVersion(
		[out]long* arg_1,
		[out]long* arg_2);

	long Proc37_UtcApi_DownloadLatestSettings2(
		[in]long arg_1,
		[in]long arg_2,
		[in]long arg_3);

	long Proc38_UtcApi_DownloadLatestSettingsForNamespace2(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]long arg_6);

	long Proc39_UtcApi_DownloadLatestSettingsForNamespaceAsync2(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in]long arg_6);
}
